using System.Collections.Generic;

namespace SAE_dev_1
{
    internal class Cartes
    {
        public static readonly string[,] CARTE_MAISON = new string[10, 20]
        {
            {
                "mur_no",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_ne"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            {
                "mur_so",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_se"
            },
        };

        public static readonly string[][,] CARTES = new string[][,]
        {
            CARTE_MAISON
        };

        public static readonly string[] NOMS_CARTES = new string[]
        {
            "La maison",
            "Le jardin"
        };

        //                           nom     x    y    rotation
        public static readonly List<(string, int, int, int)>[] OBJECTS_CARTES = new List<(string, int, int, int)>[]
        {
            new List<(string, int, int, int)>
            {
                ("porte", 10, 9, 180)
            }
        };
    }
}
