using System.Collections.Generic;

namespace SAE_dev_1
{
    internal class Cartes
    {
        public static readonly string[,] CARTE_MAISON = new string[10, 20]
        {
            // Y = 0
            {
                "mur_no",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_n",
                "mur_ne"
            },
            // Y = 1
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 2
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 3
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 4
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 5
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 6
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 7
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 8
            {
                "mur_o",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "planches",
                "mur_e"
            },
            // Y = 9
            {
                "mur_so",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_s",
                "mur_se"
            },
        };
        public static readonly string[,] CARTE_JARDIN = new string[10, 20]
        {
            // Y = 0
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 1
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 2
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 3
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "chemin_L_0",
                "chemin_I_0",
                "chemin_I_0",
                "chemin_L_90",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 4
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "chemin_I_270",
                "chemin",
                "chemin",
                "chemin_I_90",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 5
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "chemin_I_270",
                "chemin",
                "chemin",
                "chemin_I_90",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 6
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "chemin_L_270",
                "chemin_I_180",
                "chemin_I_180",
                "chemin_L_180",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 7
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 8
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
            // Y = 9
            {
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe",
                "herbe"
            },
        };

        public static readonly string[][,] CARTES = new string[][,]
        {
            CARTE_MAISON,
            CARTE_JARDIN
        };

        public static readonly string[] NOMS_CARTES = new string[]
        {
            "La maison",
            "Le jardin"
        };

        //                           nom     x    y    rotation
        // Si rotation = null, rotation est aléatoire
        public static readonly List<Objet>?[] OBJETS_CARTES = new List<Objet>?[]
        {
            new List<Objet>
            {
                new Objet("porte", 10, 9, 180, false, (mainWindow, objet) =>
                    {
                        mainWindow.derniereApparition = 0;
                        mainWindow.ChangerCarte(1);
                    }
                )
            },
            new List<Objet>
            {
                new Objet("buisson", 3, 0, null, false, null),
                new Objet("caillou", 12, 0, 0, false, (mainWindow, objet) =>
                {
                    if (mainWindow.bombe)
                    {
                        mainWindow.bombe = false;
                        objet.NeReapparaitPlus = true;
                        mainWindow.CanvasJeux.Children.Remove(objet.RectanglePhysique);
                    }
                }),

            }
        };

    }
}
